### ISSUE TITLE
合作请求

### ISSUE THREAD

**Issue by LianZiZhou** [cjyaddone/ChatWaifu#1]
我是来自 kamiya.dev 的开发者，我们目前正在将精力投入于 https://github.com/sudoskys/Openaibot 与 https://gitlab.com/MiuliKain/Kamiya-ProductUI 的开发中，我们运营的服务以公益的方式提供NovelAI图像生成/ChatGPT Like Demo。
我们目前希望在我们的服务中使用TTS并且仍处于寻找框架的阶段。近日在B站看到了您的项目，如果能与您取得合作将给我们的项目带来相当大的帮助。
因为没有找到您的公开联系方式所以只能以这种方式向您发送信息，为百忙之中的打扰感到抱歉。
我们非常想和您取得合作，我的联系方式是QQ325176292/TG @lian_zi_zhou，期待与您的进一步联系。

Lian Zhou
lianzhou@kamiya.dev

**Comment by MuBai-He** [comment]
QQ已加
