### ISSUE TITLE
[请教] 训练与推理跨语言时的效果

### ISSUE THREAD

**Issue by Ethkuil** [cjyaddone/ChatWaifu#15]
目前看作者主要是在日语素材上训练模型的，请问这样训练出来的模型如果用于其他语言，如汉语普通话，效果如何？

更具体地说，请问在日语素材中训练出来的音色、说话习惯是否会导致表述普通话内容时显得很不自然（俗称的大佐口音）？

**Comment by MuBai-He** [comment]
效果很差，会有大佐音。中文好的可以看派濛

**Comment by Ethkuil** [comment]
谢谢回答。有点可惜😥。即使是用 中文TTS 生成音频、再用 在日语上训练好的模型 变换音色，也难以避免大佐音吗？

> 中文好的可以看派濛

尝试搜索了一番，但还是没能找到相关内容，请问有更清晰的导引（如链接）吗？

**Comment by MuBai-He** [comment]
【【原神】派蒙Vtuber出道计划——基于AI深度学习VITS和VSeeFace的派蒙语音合成/套皮-哔哩哔哩】 https://b23.tv/uvDFHNZ

**Comment by Ethkuil** [comment]
了解了，谢谢。虽然和我的初衷不太一样。
