### ISSUE TITLE
是要安装pyopenjtalk而不是openjtalk吧

### ISSUE THREAD

**Issue by AlexisCAM** [cjyaddone/ChatWaifu#16]
requirements里写的openjtalk，但装不上。改成pyopenjtalk就行了

**Comment by MuBai-He** [comment]
都可以，openjtalk需要c编译器编译。pyopenjtalk方便点

**Comment by AlexisCAM** [comment]
@MuBai-He 好的。虽然不知道openjtalk咋装哈哈
