### ISSUE TITLE
M1 Mac python install error when installing openjtalk>=0.3.0.dev2

### ISSUE THREAD

**Issue by kimyLee** [cjyaddone/ChatWaifu#21]
error msg like:
Collecting unidecode (from -r requirements.txt (line 6))
  Using cached Unidecode-1.3.6-py3-none-any.whl (235 kB)
Collecting openjtalk>=0.3.0.dev2 (from -r requirements.txt (line 7))
  Using cached openjtalk-0.3.0.dev3.tar.gz (24.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/15/15/fb29ebea31d9b0fbe72b8547c9221dda17df8e23e3b4f2eb326eec07966a/openjtalk-0.3.0.dev3.tar.gz (from https://pypi.org/simple/openjtalk/): Requested openjtalk>=0.3.0.dev2 from https://files.pythonhosted.org/packages/15/15/fb29ebea31d9b0fbe72b8547c9221dda17df8e23e3b4f2eb326eec07966a/openjtalk-0.3.0.dev3.tar.gz (from -r requirements.txt (line 7)) has inconsistent version: expected '0.3.0.dev3', but metadata has '0.3.0'
  Using cached openjtalk-0.3.0.dev2.tar.gz (24.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/zhonghaoli/miniforge3/envs/py30/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()

**Comment by MuBai-He** [comment]
try to install pyopenjtalk
